/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NumberHandler */

#ifndef _Included_NumberHandler
#define _Included_NumberHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NumberHandler
 * Method:    powIntTo2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NumberHandler_powIntTo2
  (JNIEnv *, jclass, jint);

/*
 * Class:     NumberHandler
 * Method:    divideBy2Double
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_NumberHandler_divideBy2Double
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     NumberHandler
 * Method:    subtract10fromFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_NumberHandler_subtract10fromFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     NumberHandler
 * Method:    addAuthorToString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NumberHandler_addAuthorToString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
